name = "FindPeaks2"
uuid = "7ffb45d2-0618-4371-ac45-d24d5e1e2ebc"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
